name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/action-setup-conda@master
      with:
        conda-version: '4.8'         # optional. Version of conda to use for base evironment.
        conda-build-version: '3.17'  # optional. If not provided conda build is not installed.
    - run: conda create --name loop python=3.6
    - name: Using PowerShell Core
      shell: bash -l {0}
      run: |
        conda activate loop
        FOR /F "delims=~" %f in (requirements.txt) DO conda install --yes "%f -c conda-forge" || pip install "%f"
        pip install .
        conda info
        conda list
