name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: goanpeca/action-setup-conda@master
      with:
        conda-version: '4.8'         # optional. Version of conda to use for base evironment.
        conda-build-version: '3.17'  # optional. If not provided conda build is not installed.
    - run: conda create --name loop python=3.6
    - name: Installing loop structural
      shell: pwsh
      run: |
        conda activate loop
        conda install meshpy -c conda-forge
        pip install -r requirements.txt
        pip install .
        conda info
        conda list
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

